name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch: {}

jobs:
  upload-image:
    name: Build and upload Docker image
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker builder
        uses: docker/setup-buildx-action@v3

      - name: Login to container registry
        id: login-cr
        uses: yc-actions/yc-cr-login@v3
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

      - name: Build and upload image to registry
        env:
          CR_REGISTRY: crp4javlgtod0hm1kcho
          CR_REPOSITORY: utd-frontend
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
